services:
  - docker

install: true

before_script:
  - docker swarm init
  - cd
  - git clone https://github.com/akayunov/pyide.git

script:
  - cd ~/pyide
  - ./test/run-test.sh all
  - ./test/run-test.sh cov push

after_success: true

after_failure: true
