services:
  - docker

install: true

before_script:
  - docker swarm init
  - docker pull registry.hub.docker.com/akayunov/pyide:latest
  - docker pull registry.hub.docker.com/akayunov/pyide-test:latest
  - cd
  - git clone https://github.com/akayunov/pyide.git

script:
  - cd ~/pyide
  - ./test/run-test.sh all push

after_success: true

after_failure: true
